import Layout from 'components/layout/Layout';
import PopulationGraph from 'components/population/PopulationGraph';
import PrefecturesFilter from 'components/prefectures/PrefecturesFilter';
import Head from 'next/head';
import { useState } from 'react';
import styles from 'styles/index.module.scss';

const App = () => {
  const [selectedPrefList, setPrefList] = useState<Prefecture[]>([]);
  const handlePushCode = (code: number, name: string) => {
    const newSelectedPrefList = [...selectedPrefList];
    newSelectedPrefList.push({ code, name });
    setPrefList(newSelectedPrefList);
  };
  const handlePopCode = (code: number) => {
    const newSelectedPrefList = [...selectedPrefList].filter((i) => i.code !== code);
    setPrefList(newSelectedPrefList);
  };
  const handleClear = () => {
    setPrefList([]);
  };

  return (
    <>
      <Head>
        <title>Population Transition Graph in Japan</title>
        <meta name="description" content="Generated by Next.js & RESAS API" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className={styles.container}>
          <PrefecturesFilter
            selectedPrefList={selectedPrefList}
            onChange={(code: number, name: string, isCheck?: boolean) => {
              if (isCheck) {
                handlePushCode(code, name);
              } else {
                handlePopCode(code);
              }
            }}
            onClear={handleClear}
          />
          <PopulationGraph selectedPrefList={selectedPrefList} />
        </div>
      </Layout>
    </>
  );
};

export default App;
