name: Deploy Check

on:
  push:
    branches:
      - 'main'

jobs:
  verify:
    name: 'Verify deployment source'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile

      - name: Lint Check
        run: yarn lint

      - name: Run Unit Test
        run: yarn test:unit

      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: CI Build and Start Application
        env:
          NEXT_PUBLIC_RESAS_API_ENDPOINT: ${{ secrets.NEXT_PUBLIC_RESAS_API_ENDPOINT }}
          NEXT_PUBLIC_RESAS_API_KEY: ${{ secrets.NEXT_PUBLIC_RESAS_API_KEY }}
          CI: true
        run: |
          yarn build
          yarn start &
      - name: Run E2E Test
        run: yarn test:e2e

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report
